//! Deliberate runtime allow-list; third-party licenses travel with the worker.
use praxis_plugin_api::web::PackagedAsset;
macro_rules! asset {
    ($path:literal) => {
        PackagedAsset {
            path: $path,
            bytes: include_bytes!(concat!("../../../", $path)),
            executable: false,
            dashboard: true,
        }
    };
}
pub const ASSETS: &[PackagedAsset] = &[
    asset!("plugins/vm/novnc/core/base64.js"),
    asset!("plugins/vm/novnc/core/crypto/aes.js"),
    asset!("plugins/vm/novnc/core/crypto/bigint.js"),
    asset!("plugins/vm/novnc/core/crypto/crypto.js"),
    asset!("plugins/vm/novnc/core/crypto/des.js"),
    asset!("plugins/vm/novnc/core/crypto/dh.js"),
    asset!("plugins/vm/novnc/core/crypto/md5.js"),
    asset!("plugins/vm/novnc/core/crypto/rsa.js"),
    asset!("plugins/vm/novnc/core/decoders/copyrect.js"),
    asset!("plugins/vm/novnc/core/decoders/hextile.js"),
    asset!("plugins/vm/novnc/core/decoders/jpeg.js"),
    asset!("plugins/vm/novnc/core/decoders/raw.js"),
    asset!("plugins/vm/novnc/core/decoders/rre.js"),
    asset!("plugins/vm/novnc/core/decoders/tight.js"),
    asset!("plugins/vm/novnc/core/decoders/tightpng.js"),
    asset!("plugins/vm/novnc/core/decoders/zrle.js"),
    asset!("plugins/vm/novnc/core/deflator.js"),
    asset!("plugins/vm/novnc/core/display.js"),
    asset!("plugins/vm/novnc/core/encodings.js"),
    asset!("plugins/vm/novnc/core/inflator.js"),
    asset!("plugins/vm/novnc/core/input/domkeytable.js"),
    asset!("plugins/vm/novnc/core/input/fixedkeys.js"),
    asset!("plugins/vm/novnc/core/input/gesturehandler.js"),
    asset!("plugins/vm/novnc/core/input/keyboard.js"),
    asset!("plugins/vm/novnc/core/input/keysym.js"),
    asset!("plugins/vm/novnc/core/input/keysymdef.js"),
    asset!("plugins/vm/novnc/core/input/util.js"),
    asset!("plugins/vm/novnc/core/input/vkeys.js"),
    asset!("plugins/vm/novnc/core/input/xtscancodes.js"),
    asset!("plugins/vm/novnc/core/ra2.js"),
    asset!("plugins/vm/novnc/core/rfb.js"),
    asset!("plugins/vm/novnc/core/util/browser.js"),
    asset!("plugins/vm/novnc/core/util/cursor.js"),
    asset!("plugins/vm/novnc/core/util/element.js"),
    asset!("plugins/vm/novnc/core/util/events.js"),
    asset!("plugins/vm/novnc/core/util/eventtarget.js"),
    asset!("plugins/vm/novnc/core/util/int.js"),
    asset!("plugins/vm/novnc/core/util/logging.js"),
    asset!("plugins/vm/novnc/core/util/strings.js"),
    asset!("plugins/vm/novnc/core/websock.js"),
    asset!("plugins/vm/novnc/vendor/pako/LICENSE"),
    asset!("plugins/vm/novnc/vendor/pako/README.md"),
    asset!("plugins/vm/novnc/vendor/pako/lib/utils/common.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/adler32.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/constants.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/crc32.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/deflate.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/gzheader.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/inffast.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/inflate.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/inftrees.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/messages.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/trees.js"),
    asset!("plugins/vm/novnc/vendor/pako/lib/zlib/zstream.js"),
    asset!("plugins/vm/novnc/LICENSE.txt"),
    asset!("plugins/vm/novnc/docs/LICENSE.MPL-2.0"),
    asset!("plugins/vm/novnc/docs/LICENSE.BSD-3-Clause"),
    asset!("plugins/vm/ui/page.html"),
    asset!("plugins/vm/ui/vm.js"),
    asset!("plugins/vm/ui/vm.css"),
    asset!("plugins/vm/ui/vnc.html"),
];
